name: Auto Merge Workflow

on:
  push:
    branches:
      - featured-branch

jobs:
  automate_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Feature Branch
        run: |
          git checkout -b new-branch
          # Make modifications here (e.g., using scripts or commands)

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Automated changes"
      
      - name: Push Changes
        run: git push origin new-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: new-branch
          title: Automated Pull Request
          labels: automation

  merge_into_dev:
    runs-on: ubuntu-latest
    needs: automate_pull_request
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge Pull Request into Dev
        run: |
          git fetch origin
          git checkout dev
          git pull origin dev
          git merge --no-ff new-branch -m "Merge pull request #${{ github.event.pull_request.number }}"

          # Optionally, push changes to the dev branch
          # git push origin dev

