name: Create Pull Request

on:
  push:
    branches:
      - feature-branch

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature-branch
          title: "Automated PR from feature-branch to dev"
          body: "This PR was automatically created."
          labels: "automated"
          reviewers: "ashanda"
          assignees: "ashanda"
